// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type History struct {
	ID       int64
	T        int64
	Wk       float64
	WkReset  sql.NullInt64
	Ses      sql.NullFloat64
	SesReset sql.NullInt64
	Tier     string
	Cost     sql.NullFloat64
	Session  sql.NullString
}

type Kv struct {
	Key       string
	Value     string
	UpdatedAt int64
}

type Snapshot struct {
	Session    string
	CapturedAt int64
	Payload    string
}
