// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
	"database/sql"
)

const appendHistory = `-- name: AppendHistory :exec
INSERT INTO history (t, wk, wk_reset, ses, ses_reset, cost, session)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type AppendHistoryParams struct {
	T        int64
	Wk       float64
	WkReset  sql.NullInt64
	Ses      sql.NullFloat64
	SesReset sql.NullInt64
	Cost     sql.NullFloat64
	Session  sql.NullString
}

func (q *Queries) AppendHistory(ctx context.Context, arg AppendHistoryParams) error {
	_, err := q.db.ExecContext(ctx, appendHistory,
		arg.T,
		arg.Wk,
		arg.WkReset,
		arg.Ses,
		arg.SesReset,
		arg.Cost,
		arg.Session,
	)
	return err
}

const dataAge = `-- name: DataAge :one
SELECT CAST(COALESCE(max(captured_at), 0) AS INTEGER) AS newest FROM snapshots
`

// CAST(COALESCE(...)) not bare CAST: max() over an empty snapshots table (the fresh-install state)
// is NULL, and a bare CAST(max AS INTEGER) still yields NULL at runtime -> fail-scans NULL->int64 on
// first run. COALESCE(..., 0) makes the runtime value never NULL (0 = "no snapshots yet"); the outer
// CAST keeps sqlc typing newest as a clean non-null int64. The facade reads 0 as no-data (captured_at
// is always a real epoch, never 0). (bare COALESCE alone makes sqlc emit interface{}.)
func (q *Queries) DataAge(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, dataAge)
	var newest int64
	err := row.Scan(&newest)
	return newest, err
}

const envelopeFiveHour = `-- name: EnvelopeFiveHour :many
WITH latest AS (
  SELECT max(history.ses_reset) AS r FROM history
  WHERE history.ses IS NOT NULL AND history.ses_reset IS NOT NULL AND history.t >= ?1
),
kept AS (
  SELECT h.t, h.ses AS f, h.id FROM history h, latest
  WHERE h.t >= ?1 AND h.ses IS NOT NULL
    AND CASE WHEN latest.r IS NOT NULL
             THEN h.ses_reset IS NOT NULL AND latest.r - h.ses_reset <= 300
             ELSE h.ses_reset IS NULL END
)
SELECT kept.t,
       CAST(max(kept.f) OVER (ORDER BY kept.t, kept.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS REAL) AS running,
       (SELECT r FROM latest) AS reset
FROM kept ORDER BY kept.t, kept.id
`

type EnvelopeFiveHourRow struct {
	T       int64
	Running float64
	Reset   interface{}
}

func (q *Queries) EnvelopeFiveHour(ctx context.Context, cutoff int64) ([]EnvelopeFiveHourRow, error) {
	rows, err := q.db.QueryContext(ctx, envelopeFiveHour, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvelopeFiveHourRow{}
	for rows.Next() {
		var i EnvelopeFiveHourRow
		if err := rows.Scan(&i.T, &i.Running, &i.Reset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const envelopeWeekly = `-- name: EnvelopeWeekly :many
WITH latest AS (
  SELECT max(history.wk_reset) AS r FROM history
  WHERE history.wk IS NOT NULL AND history.wk_reset IS NOT NULL AND history.t >= ?1
),
kept AS (
  SELECT h.t, h.wk AS f, h.id FROM history h, latest
  WHERE h.t >= ?1 AND h.wk IS NOT NULL
    AND CASE WHEN latest.r IS NOT NULL
             THEN h.wk_reset IS NOT NULL AND latest.r - h.wk_reset <= 300
             ELSE h.wk_reset IS NULL END
)
SELECT kept.t,
       CAST(max(kept.f) OVER (ORDER BY kept.t, kept.id ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS REAL) AS running,
       (SELECT r FROM latest) AS reset
FROM kept ORDER BY kept.t, kept.id
`

type EnvelopeWeeklyRow struct {
	T       int64
	Running float64
	Reset   interface{}
}

// Two-pass running-max mirror of burn.Envelope (see docs/sqlite-storage-design.md):
// latest = max weekly reset in the window; kept = rows within the 300s jitter bucket of it
// (or, when there is no latest, rows with a NULL reset); running = arrival-order running max.
// Every latest column is qualified (history.wk) and the computed running column is CAST, or
// sqlc's analyzer errors / emits interface{}. reset stays un-CAST: sqlc cannot type an aggregate
// (max wk_reset) inside a scalar subquery, so it emits interface{} (NOT sql.NullInt64). That is
// deliberate: interface{} preserves the nullability the !hasLatest path needs (NULL->nil, int->int64),
// and the store facade normalizes it to sql.NullInt64. CASTing reset would type it non-nullable int64
// and fail-scan on the NULL (no-latest) case, so we do NOT CAST it.
func (q *Queries) EnvelopeWeekly(ctx context.Context, cutoff int64) ([]EnvelopeWeeklyRow, error) {
	rows, err := q.db.QueryContext(ctx, envelopeWeekly, cutoff)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []EnvelopeWeeklyRow{}
	for rows.Next() {
		var i EnvelopeWeeklyRow
		if err := rows.Scan(&i.T, &i.Running, &i.Reset); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getKV = `-- name: GetKV :one
SELECT value FROM kv WHERE key = ?
`

func (q *Queries) GetKV(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getKV, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const lastSessionRow = `-- name: LastSessionRow :one
SELECT id, t, wk, wk_reset, ses, ses_reset, cost, session FROM history
WHERE (?1 IS NULL OR session = ?1)
ORDER BY id DESC LIMIT 1
`

func (q *Queries) LastSessionRow(ctx context.Context, session interface{}) (History, error) {
	row := q.db.QueryRowContext(ctx, lastSessionRow, session)
	var i History
	err := row.Scan(
		&i.ID,
		&i.T,
		&i.Wk,
		&i.WkReset,
		&i.Ses,
		&i.SesReset,
		&i.Cost,
		&i.Session,
	)
	return i, err
}

const pruneHistory = `-- name: PruneHistory :execrows
DELETE FROM history WHERE t < ?
`

func (q *Queries) PruneHistory(ctx context.Context, t int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneHistory, t)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const pruneSnapshots = `-- name: PruneSnapshots :execrows
DELETE FROM snapshots WHERE captured_at < ?
`

func (q *Queries) PruneSnapshots(ctx context.Context, capturedAt int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, pruneSnapshots, capturedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const putKV = `-- name: PutKV :exec
INSERT INTO kv (key, value, updated_at) VALUES (?, ?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at
`

type PutKVParams struct {
	Key       string
	Value     string
	UpdatedAt int64
}

func (q *Queries) PutKV(ctx context.Context, arg PutKVParams) error {
	_, err := q.db.ExecContext(ctx, putKV, arg.Key, arg.Value, arg.UpdatedAt)
	return err
}

const putSnapshot = `-- name: PutSnapshot :exec
INSERT INTO snapshots (session, captured_at, payload) VALUES (?, ?, ?)
ON CONFLICT(session) DO UPDATE SET captured_at = excluded.captured_at, payload = excluded.payload
`

type PutSnapshotParams struct {
	Session    string
	CapturedAt int64
	Payload    string
}

func (q *Queries) PutSnapshot(ctx context.Context, arg PutSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, putSnapshot, arg.Session, arg.CapturedAt, arg.Payload)
	return err
}

const snapshots = `-- name: Snapshots :many
SELECT session, captured_at, payload FROM snapshots
`

func (q *Queries) Snapshots(ctx context.Context) ([]Snapshot, error) {
	rows, err := q.db.QueryContext(ctx, snapshots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Snapshot{}
	for rows.Next() {
		var i Snapshot
		if err := rows.Scan(&i.Session, &i.CapturedAt, &i.Payload); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const wkPoints = `-- name: WkPoints :many
SELECT CAST(wk_reset AS INTEGER) AS bnd,
       CAST((t / 60) * 60 AS INTEGER) AS minute,
       CAST(max(wk) AS REAL) AS mx
FROM history
WHERE wk_reset IS NOT NULL
GROUP BY wk_reset, (t / 60) * 60
ORDER BY wk_reset, (t / 60) * 60
`

type WkPointsRow struct {
	Bnd    int64
	Minute int64
	Mx     float64
}

// Per (weekly reset boundary, minute) the max wk%, feeding calib.wkRuns' run reconstruction over the
// FULL history (no time cutoff, unlike the envelope). The bulky per-minute-max aggregation is SQL; the
// run-splitting stays in Go. CAST the computed columns or sqlc emits interface{}; wk_reset is CAST too
// (the WHERE guarantees non-null) so bnd is a clean int64. minute = (t/60)*60 mirrors the Go floor.
func (q *Queries) WkPoints(ctx context.Context) ([]WkPointsRow, error) {
	rows, err := q.db.QueryContext(ctx, wkPoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WkPointsRow{}
	for rows.Next() {
		var i WkPointsRow
		if err := rows.Scan(&i.Bnd, &i.Minute, &i.Mx); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
